# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWwsrdVQxVuv5YKoKei23qZCK3icd0_h
"""

app_code = '''
import streamlit as st
from streamlit_webrtc import webrtc_streamer, VideoProcessorBase
import torch
import av
import cv2

@st.cache_resource
def load_model():
    return torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt', force_reload=True)

model = load_model()

class YOLOVideoProcessor(VideoProcessorBase):
    def recv(self, frame):
        img = frame.to_ndarray(format="bgr24")
        results = model(img)
        results.render()
        rendered_img = results.ims[0]
        return av.VideoFrame.from_ndarray(rendered_img, format="bgr24")

st.set_page_config(page_title="YOLO Real-Time Eye Detection", layout="centered")
st.title("👁️ Deteksi Kondisi Mata Real-Time")
st.markdown("Menggunakan YOLOv5 + Webcam via Streamlit")

webrtc_streamer(
    key="yolo-eye",
    video_processor_factory=YOLOVideoProcessor,
    media_stream_constraints={"video": True, "audio": False},
    async_processing=True
)
'''

# Tulis ke file app.py
with open("app.py", "w") as f:
    f.write(app_code)

# Download ke komputer lokal
from google.colab import files
files.download("app.py")